pode_ir(jaboticabal, ribeirao_preto, 50).
pode_ir(jaboticabal, araraquara, 62).
pode_ir(jaboticabal, taquaritinga, 25).
pode_ir(taquaritinga, araraquara, 56).
pode_ir(araraquara, ribeirao_preto, 79).
pode_ir(araraquara, jau, 66).
pode_ir(araraquara, sao_carlos, 38).
pode_ir(sao_carlos, jau, 85).
pode_ir(sao_carlos, brotas, 59).
pode_ir(jau, brotas, 47).
pode_ir(brotas, piracicaba, 71).
pode_ir(ribeirao_preto, sao_carlos, 87).
pode_ir(ribeirao_preto, porto_ferreira, 77).
pode_ir(porto_ferreira, sao_carlos, 47).
pode_ir(porto_ferreira, pirassununga, 17).
pode_ir(pirassununga, sao_carlos, 52).
pode_ir(pirassununga, rio_claro, 57).
pode_ir(pirassununga, limeira, 65).
pode_ir(rio_claro, sao_carlos, 53).
pode_ir(rio_claro, limeira, 28).
pode_ir(rio_claro, piracicaba, 35).
pode_ir(limeira, piracicaba, 32).